apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  namespace: my-bank
  labels:
    name: my-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      apptype: web-backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        apptype: web-backend
    spec:
      containers:
      - name: my-web
        image: 22csl258/mysimplewebapplication:tagname
        ports:
        - containerPort: 9001

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-bank
  labels:
    app: my-service
spec:
  type: NodePort
  ports:
    - port: 9001
      targetPort: 8080
      nodePort: 30007
  selector:
    apptype: web-backend